# hpa.yaml
# This file configures horizontal pod autoscaling to ensure scalability.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: content-authoring-assistant-hpa  # HPA for the content-authoring assistant.
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: content-authoring-assistant  # Referring to the deployment for scaling.
  minReplicas: 3  # Minimum number of pods to run.
  maxReplicas: 10  # Maximum number of pods, scaling based on load.
  targetCPUUtilizationPercentage: 60  # Scale when CPU exceeds 60%.